### ISSUE TITLE
added installation python-setuptools for Centos6. 

### ISSUE THREAD

**Issue by zakabluk** [lean-delivery/ansible-role-atg-platform-patching#2]
##### SUMMARY
Maybe will better when you added install package
python-setuptools
before executing task "Install pexpect using ansible easy_install module" only for Centos6.

##### ISSUE TYPE
 - Feature Idea

##### OS / ENVIRONMENT
Centos 6

##### STEPS TO REPRODUCE
Run role on Centos6.

##### EXPECTED RESULTS
Installation of package.

##### ACTUAL RESULTS
```
fatal: [10.68.72.8]: FAILED! => changed=true
  cmd:
  - easy_install
  - pexpect
  delta: '0:00:00.084436'
  end: '2018-08-20 12:10:53.902341'
  msg: non-zero return code
  rc: 1
  start: '2018-08-20 12:10:53.817905'
  stderr: 'error: Could not find suitable distribution for Requirement.parse(''pexpect'')'
  stderr_lines:
  - 'error: Could not find suitable distribution for Requirement.parse(''pexpect'')'
  stdout: |-
    Searching for pexpect
    Reading http://pypi.python.org/simple/pexpect/
    Couldn't find index page for 'pexpect' (maybe misspelled?)
    Scanning index of all packages (this may take a while)
    Reading http://pypi.python.org/simple/
    No local packages or download links found for pexpect
  stdout_lines: <omitted>
```

```

```

**Comment by anastacia-maletskaya-epam** [comment]
Could you please provide error log from system and output of running easy_install? i'm asking because python-setuptools is required to be installed to have ability to use easy_install. it doesn't contain pexpect.
Here is an example
https://centos.pkgs.org/6/centos-x86_64/python-setuptools-0.6.10-4.el6_9.noarch.rpm.html

**Comment by zakabluk** [comment]
Hi!  Sorry for my long response time. I have just finished my new test:  aws ami "ami-e3fdd999" as node for install roles and ansible 2.6.4. 
In time executed role I had:
```
TASK [lean_delivery.atg_platform_patching : Install pexpect using ansible easy_install module] *******************************************************************************************************************************************
fatal: [10.68.72.105]: FAILED! => {"changed": false, "msg": "warning: install_lib: 'build/lib' does not exist -- no Python modules to install\nerror: Setup script exited with error: build/bdist.linux-x86_64/egg/EGG-INFO/zip-safe: No such file or directory\n"}
```
but necessary package was installed by python:  name: "Install pexpect using python easy_install"
I close a task.
